soofstad/react-oauth2-pkce

src/Types.ts
A quick PR to fix the AuthProvider type, as `children` property can be any `ReactNode` type.
=> fix: wrong AuthProvider children type

src/AuthContext.tsx, src/Types.ts, src/authentication.ts, src/package.json
The purpose of these changes is compatibility with FusionAuth.
These changes add a configuration key of 'tokenPostEncoding' as a pseudo
enumeration that is either 'multi-part' ( the default ) or 'url-encoded'.
Setting this configuration key to a value of 'url-encoded' will cause
the token requests to be sent as 'application/x-www-form-urlencoded'
POSTs. ( FusionAuth does not support multi-part POSTS for tokens )
This is accomplished by explicitly typing the token request data and
passing that into the function performing the fetch. The actual POST
body is then built along with the proper headers in the function
doing the fetching.
This commit also increases the code verifier random length to 96.
( FusionAuth seems to reject shorter code verifiers )
**EDIT** It looks like the request for a …
=> POST encoding to 'application/x-www-form-urlencoded' per OAuth 2.0 spec

README.md, src/Types.ts, src/authentication.ts, src/index.js, src/package.json, src/validateAuthConfig.ts, tests/token_request.test.tsx
Some auth providers accept or require non-standard parameters for the authentication request.
This commit adds an additional optional configuration parameter for providing arbitrary extra parameters to that request.
closes #25
=> feat: support extra parameters in the auth request

README.md, src/AuthContext.tsx, src/Types.ts, src/authentication.ts, src/decodeJWT.ts, src/httpUtils.ts, src/index.js, src/package.json, src/timeUtils.ts, tests/authentication.test.ts
Fix a bug where the provided logout function did not redirect the browser to the authentication providers logout endpoint.
closes #23
=> fix: logout function did not redirect

src/AuthContext.tsx, src/Hooks.tsx, src/Types.ts, src/index.js
As presented in #30 the library currently does a slightly risky, undefined redirect whenever it notices that the refresh token has expired.
This PR adds an option to TAuthConfig: `onRefreshTokenExpire?: (event: TRefreshTokenExpiredEvent) => void`. This callback allows users to react to the tokens expiring, and then lets the users handle it however they want. The `login` function is also exposed in the event to allow the users to e.g. do `onRefreshTokenExpire: (event) => window.confirm("Expired. Login again?) && event.login()`.
Closes #30.
=> feat: RefreshTokenExpired handler

.github/CODEOWNERS, package.json, src/AuthContext.tsx, src/index.js, src/package.json
Fixes two bugs:
- Wrong type for caught error in 'get token with refresh_token'-request
- Failed token refresh on page load did not trigger a new login, causing users to have to logout, and -in again manually.
NOTE: Failed silent refresh will still fail.  There are two options to handle this;
1. Show a message to the user that he/she should refresh their browser
2. Provide the `onRefreshTokenExpired` config parameter, and handle the event in  your callback
=> fix: bad handling of failed token refresh

examples/microsoft-auth-provider/web-app/package.json, src/AuthContext.tsx, src/Types.ts, src/authentication.ts, src/errors.ts, src/httpUtils.ts, src/package.json, tests/auth-util.test.ts
This commit changes how failed refresh requests are handled.
Since we often have to assume the refreshToken expire time, it will sometimes be wrong. Therefore, we might make a refresh request with an expired refreshToken.
This change make sure all 400 status codes on the refresh request are handled as if the refreshToken has expired. Even if there might be other reasons.
closes #38
=> fix: handle all 400 refresh requests as "expired"

README.md, src/Types.ts, src/authentication.ts
Add new config extraLogoutParameters. Use the extra logout parameters in the logout request.
To support non-standard logout parameters.
https://github.com/soofstad/react-oauth2-pkce/issues/51
=> Add support to non-standard logout parameters

src/AuthContext.tsx
Fixes a bug where the "initial" flag was not passed to "handleExpiredRefreshToken()" on first page load when the refreshToken was expired.
This caused the "onRefreshTokenExpire()" callback to be called on pageload.
=> fix: autologin when loading page w/ expired refreshToken

src/AuthContext.tsx, src/package.json, src/tsconfig.json
Moves 
```typescript
window.history.replaceState(null, '', window.location.pathname) // Clear ugly url params
```
into a `finally`-clause, to ensure it is called both for successful and failing promises. 
Users reported broken auth states that were not remedied by refreshing the page.
None
=> fix: broken-code-state

README.md, src/AuthContext.tsx, src/Types.ts
Some auth providers (like AzureAD) don't send information about access/refresh token expiration time in token response.
This change allows the user to provide access/refresh token expiration time via config.
```tsx
import { AuthContext, AuthProvider, TAuthConfig, TRefreshTokenExpiredEvent } from "react-oauth2-code-pkce"
const authConfig: TAuthConfig = {
...
tokenExpiresIn: 3600,
refreshTokenExpiresIn: 86400 
}
const UserInfo = (): JSX.Element => {
const {token, tokenData} = useContext<IAuthContext>(AuthContext)
return <>
<h4>Access Token</h4>
<pre>{token}</pre>
<h4>User Information from JWT</h4>
<pre>{JSON.stringify(tokenData, null, 2)}</pre>
</>
}
ReactDOM.render(<AuthProvider authConfig={authConfig}>
<UserInfo/>
</AuthProvider>
, document.getElementById('root'),
)
```
=> feature: configure token expiration time

src/AuthContext.tsx
Moves the call to `setLoginInProgress(false)` from within a function call and out into a `.finally`-call, which is always run.
Current location could possibly not happen if the function call failed.
None. Mentioned in https://github.com/soofstad/react-oauth2-pkce/pull/66#discussion_r1126259668
=> fix: move the `setLoginInProgress(false)`

src/AuthContext.tsx
Previously, errors were not cleared when logging out. I can not see a single case where it's helpful to keep errors after logging out. I'm (in my application) subscribing to the `error` state and showing a log-out button whenever it's not null, which currently doesn't do anything (it does log out, but the `error` state isn't cleared). 
This PR remedies that by clearing the error state when logging out.
None.
=> Add `setError(null)` to logOut function

src/AuthContext.tsx
- Always decode idToken
- idToken is always a JWT, per https://openid.net/specs/openid-connect-core-1_0.html#IDToken
Therefore, we can always decode it. This allows for getting `idTokenData` even if the `accessToken` is not a JWT.
> **Note**
>Try catch on idToken decode _should_ not be needed. But this would potentially be a BREAKING CHANGE if we skipped it. And I think it's good to be forgiving with these "non-crucial" functionality.
closes #74
=> fix: always decode idToken

src/Hooks.tsx
Signed-off-by: Sebastian Vittersø <svit@equinor.com>
We had a potential bug in `Hooks.tsx` where we only checked if `!value`, where `false` and `null` should not trigger, only `undefined`.
This is now changed to only trigger with `value === undefined`. 
Closes #78.
=> fix: if-clause should check for undefined

package.json, src/AuthContext.tsx, src/authentication.ts, src/pkceUtils.ts, tests/auth-request.test.tsx, tests/insecure-environment.test.tsx, tests/jestSetup.js, tests/token-request.test.tsx
- Create a check for availability of `crypto.subtle` and throw error if missing
- Update testing dependencies
- Remove unnecessary context wrapper in tests
- Added test for "unsecure-environment"
see #73 
closes #73
=> fix: check and raise error for insecure context

src/AuthContext.tsx
This PR prevents concurrent fetchTokens call (after OAuth return) and autoLogin 
In v1.13.4 the effect has been changed, where the return is not in the correct scope
This PR fixes issue #92
=> Fixed issue #92 Concurrent fetchTokens and autoLogin trigger

src/decodeJWT.ts
Fix the error message about JWT => JSON Web Token rather than Java Web Token
Better error message
No issue needed
=> Fix error message to JSON Web Token

src/Types.ts, src/authConfig.ts, src/authentication.ts, tests/login.test.tsx
Makes the `scope` property internally optional as well (optional = allowed to be `undefined`). Also hides it from requests if it's set to `undefined`, as per the spec.
We didn't adhere to the spec. Now we do (more closely at least). 
Closes #96.
=> fix: make scope optional and don't send it if undefined

src/authentication.ts
- Send any parameters defined in "extraTokenParameters" in "fetchWithRefreshToken()"
- Some auth servers also require special parameters with the "refresh_token" grant type 
closes #102
=> feature: use extraTokenParams in refresh request

README.md, src/AuthContext.tsx, src/Hooks.tsx, src/Types.ts, src/authConfig.ts, tests/jestSetup.js, tests/login.test.tsx, tests/test-utils.tsx
Updated the config, as well as the `useBrowserStorage` hook to accept a key prefix. 
In the config defaults, functionality will remain the same as it is without this code change in order to maintain backwards-compatibility.
Some developers may want/need the ability to change the storage key names
None
=> Add support for changing the browser storage key prefix

.eslintrc.json, .pre-commit-config.yaml, package.json, src/AuthContext.tsx, tests/jestSetup.js
Adds a check to `setTokenData(decodeJWT(token))` to verify that `token !== undefined` when doing it.
The console retrieves two errors and two warnings during startup if the user isn't logged in. Not pretty.
None.
=> fix: disable decoding undefined token

src/timeUtils.ts, tests/auth-util.test.ts
Attempt to convert recieved "expire_time" to Number.
Some auth providers might respond with a string instead of Number for the "expires_in_*" value.
closes #111
=> feat: allow expire times as strings

src/Types.ts, src/authentication.ts, tests/get_token.test.tsx
The scope parameter is not indicated in RFC7636 for inclusion in the token request. It should be removed as it causes issues with strict IDP implementations.
Removes "scope" parameter from token request
Including "scope" is a specification violation
https://github.com/soofstad/react-oauth2-pkce/issues/129
=> The token request should not include the scope parameter

README.md, src/Types.ts, src/authConfig.ts, src/authentication.ts, src/index.js, tests/auth-util.test.ts
Adds a config parameter to opt-out of sending "scope" in the refresh request.
- Some auth servers will throw an error if the "scope" parameter is in the refresh request
relates to issues raised in #129
=> feat: option to opt-out of sending scope with refresh request

src/authentication.ts, tests/jestSetup.js, tests/login.test.tsx, tests/logout.test.tsx
Replaces `window.location.replace(newUrl)` with `window.location.assign(newUrl)` two places in `authentication.ts` and in the related test setup.
This change allows users to hit the browser's back-button (or hardware back-buttons) to get back to the page they were on before they were redirected to the auth-provider's login page.
Closes #97 closes #134.
=> fix: use `location.assign()` instead of `location.replace()`, to enable browser history usage

README.md, src/AuthContext.tsx, src/package.json
- Don't assume that refresh_token is always included in token response.
- Added some more "Common issues" in README
Some IDPs don't include refresh_token when requesting a token with a refresh_token
closes #137
=> fix: handle token response with no refresh_token

README.md, src/AuthContext.tsx, src/Hooks.tsx, src/authentication.ts, tests/get_token.test.tsx
First adds a `randomStagger` to refresh interval, which made it possible to share code verifier and auth state between tabs/windows (by having it in the`localStorage`).
Closes #139.
=> feat: use selected storage for auth state and code verifier (too)

examples/microsoft-auth-provider/web-app/package.json, package.json, src/AuthContext.tsx
Update packages in root- and example `package.json`, and remove eslint and react references. We now use biome for linting and formatting.
None.
=> chore: update packages in root- and example `package.json`, and remove eslint and react references

README.md, src/AuthContext.tsx, src/Types.ts, src/authentication.ts, src/index.js
- Add an optional parameter to `login()` that allows sending auth parameters others than those defined in the static config object.
fixes #145
=> feat: pass additional parameters to the login function

README.md, examples/github-auth-provider/web-app/src/index.tsx, examples/keycloak-auth-provider/web-app/src/index.tsx, examples/microsoft-auth-provider/web-app/src/index.tsx, src/AuthContext.tsx, src/Types.ts, src/index.js, tests/login.test.tsx, tests/logout.test.tsx, tests/test-utils.tsx
This commit changes the `login` function to be `logIn`. It also updates any related terminology in the docs or otherwise to match.
Function names should conventionally be in the imperative form, but the login() function didn't conform to this convention.
#115
=> feat: fix functions names & related terminology to be imperative

src/AuthContext.tsx, src/Types.ts
This pull request includes refactoring changes to add `@deprecated` notices to deprecated types and update notices of future changes. The changes ensure that developers are aware of deprecated types and upcoming changes.
=> refactor: add `@deprecated` notices to deprecated types and update notices of future changes

README.md, src/AuthContext.tsx, src/authConfig.ts, src/types.ts, tests/auth-util.test.ts
This pull request adds a new configuration option, `refreshTokenExpiryStrategy`. This option allows users to specify the refresh token expiration strategy, choosing between:
'**renewable**': The refresh token's expiration time is renewed each time it is used. 
'**absolute**': The refresh token's expiration time is fixed from its initial issuance and does not change.
We are currently using Auth0 with Absolute Expiration. Auth0 implements an absolute expiration strategy for refresh tokens, meaning the expiration time is fixed from the initial issuance and does not renew with each use. However, the library was designed with the assumption that the refresh token expiration would be renewed each time a new refresh token is requested.
This mismatch between the actual expiration behavior and the …
=> Feat: add support to refresh token absolute lifetime

src/AuthContext.tsx
It is fixing the expired token refresh bug.
In multiple cases, the expired token is not refreshed after the first refresh.
fixes [#170](https://github.com/soofstad/react-oauth2-pkce/issues/170)
=> fix: update expiring token interval on refreshInProgress change

src/AuthContext.tsx
As pointed out in #179, we currently overwrite the internal state for `idToken` every time we get a token response, but `response.id_token` is optional here, in the sense that it might only be sent for the first token, and then the auth provider can just assume the client keeps track of it. 
So we can't overwrite it with `undefined` when we don't get it at a later time. This PR makes it so.
Closes #179.
=> fix: only set/overwrite id_token if a value is returned by auth provider

README.md, src/authConfig.ts, src/authentication.ts, src/httpUtils.ts, src/types.ts, tests/auth-util.test.ts, tests/get_token.test.tsx
It enables credentials when doing fetch requests.
Specifically it enables TLS client certificate authentication for OPTIONS requests in Firefox.
This fixes 403/forbidden errors, that would happen otherwise, since the request would be done without client certificate authentication and thus fail with 403 when using Firefox.
When the server is enforcing client certificate authentication, we must set the fetch option "credentials" to "include", to ensure all browsers are allowing client certificate authentication. For example, this is required in Firefox for "OPTIONS" requests.
This will require the server to respond with proper CORS response headers, but this should already be the case (for example when using Keycloak).
If you prefer to make this configurable, I am willing to implement this, …
=> Fetch with credentials in postWithXForm()

src/AuthContext.tsx, src/decodeJWT.ts
- Decode tokens in a "useMemo" instead of a "useEffect"
- This remove one render cycle, where "loginInProgress" is false, "token" is set, but "tokenData" is undefined
none
=> fix: decode token(s) before rendering provider

src/index.js
This PR removes the `postLogout` callback given in `./src/index.js`. Its presence made me thinking this callback was actually supported and was just undocumented, cf. #187. But turns out, it seems to be just some leftover from the discussions of the issues stated below.
This clarifies that this library actually does not provide  callback that is called after logout.
Discussions that might have introduced this as an artefact:
- https://github.com/soofstad/react-oauth2-pkce/issues/156
- https://github.com/soofstad/react-oauth2-pkce/issues/157
- https://github.com/soofstad/react-oauth2-pkce/issues/158
=> Remove obsolete postLogout() callback

src/AuthContext.tsx
- Refactor `handleExpiredRefreshToken`.
- Changed logic on when to redirect to Login
- Fixes a bug that lead to `autoLogin=false` to not be respected on expired refresh token
closes #202
=> fix: autoLogin false not respected on expired refresh

README.md, src/AuthContext.tsx, src/authentication.ts, src/types.ts
It adds the ability to replace the browser history entry when redirecting to the authorization page, as well as refactors some type code and docs.
To give the ability to replace the browser history entry instead of creating a new one in some cases, and to keep the code base clean.
#210
=> feat: add replace history option

src/AuthContext.tsx
Currently, the error state is not cleared after the successful token response. The error state gets set when there is an error while getting the token. However, the error state is not cleared even if the subsequent requests were successful.
If anyone uses the `error` property to display the error. The error will always be displayed since it is not cleared after the successful token request.
closes #221
=> Fix: Reset error state after successful token response
